messages:
  no_permission: "&cУ вас нет прав на использование этой команды!"
  invalid_amount: "&cНеверное количество!"
  player_not_found: "&cИгрок не найден!"
  usage: "&fИспользование:&e /dlos <игрок> <количество>"
  given_item: "&fВы выдали &e{amount} &fпредметов игроку &e{target}"
  block_place_denied: "Вы не можете установить этот предмет!"

item:
  name: "&eСлабительное"
  lore:
    - "&7Правый клик чтобы использовать"
    - "&7Накладывает эффекты на ближайших игроков"

effects:
  sound:  # ЗВУКИ БРАТЬ ИЗ САЙТА https://helpch.at/docs/1.16.5/org/bukkit/Sound.html
    type: ENTITY_WITHER_DEATH
    volume: 1.0
    pitch: 1.0
  duration: 30 # УКАЗЫВАТЬ ВРЕМЯ В СЕКУНДАХ
  radius: 5
  potion_effects:  
    blindness: # ЭФФЕКТЫ БРАТЬ ИЗ САЙТА https://helpch.at/docs/1.16.5/org/bukkit/potion/PotionEffectType.html
      type: BLINDNESS
      level: 1 
    slowness:
      type: SLOW
      level: 2
    weakness:
      type: WEAKNESS
      level: 2
